### ISSUE TITLE
Table Management

### ISSUE THREAD

**Issue by hurshore** [emmacode/Reservly#20]
**Tasks**
- [x] Define table schema
- [x] Implement table creation
- [x] Implement table fetch
- [x] Implement table update
- [x] Implement table deletion
